<%
Dim countryNameListArr(231)
countryNameListArr(0)	 = "Republic of Korea"
countryNameListArr(1)	 = "Afghanistan"
countryNameListArr(2)	 = "Albania"
countryNameListArr(3)	 = "Algeria"
countryNameListArr(4)	 = "American Samoa"
countryNameListArr(5)	 = "Andorra"
countryNameListArr(6)	 = "Angola"
countryNameListArr(7)	 = "Anguilla"
countryNameListArr(8)	 = "Antarctica"
countryNameListArr(9)	 = "Antigua and Barbuda"
countryNameListArr(10)	 = "Argentina"
countryNameListArr(11)	 = "Armenia"
countryNameListArr(12)	 = "Aruba"
countryNameListArr(13)	 = "Australia"
countryNameListArr(14)	 = "Austria"
countryNameListArr(15)	 = "Azerbaijan"
countryNameListArr(16)	 = "Bahamas"
countryNameListArr(17)	 = "Bahrain"
countryNameListArr(18)	 = "Bangladesh"
countryNameListArr(19)	 = "Barbados"
countryNameListArr(20)	 = "Belarus"
countryNameListArr(21)	 = "Belgium"
countryNameListArr(22)	 = "Belize"
countryNameListArr(23)	 = "Benin"
countryNameListArr(24)	 = "Bermuda"
countryNameListArr(25)	 = "Bhutan"
countryNameListArr(26)	 = "Bolivia"
countryNameListArr(27)	 = "Bosnia-Herzegovina"
countryNameListArr(28)	 = "Botswana"
countryNameListArr(29)	 = "Bouvet Island"
countryNameListArr(30)	 = "Brazil"
countryNameListArr(31)	 = "Brunei Darussalam"
countryNameListArr(32)	 = "Bulgaria"
countryNameListArr(33)	 = "Burkina Faso"
countryNameListArr(34)	 = "Burundi"
countryNameListArr(35)	 = "Cambodia"
countryNameListArr(36)	 = "Cameroon"
countryNameListArr(37)	 = "Canada"
countryNameListArr(38)	 = "Cape Verde"
countryNameListArr(39)	 = "Cayman Islands"
countryNameListArr(40)	 = "Central African Republic"
countryNameListArr(41)	 = "Chad"
countryNameListArr(42)	 = "Chile"
countryNameListArr(43)	 = "China"
countryNameListArr(44)	 = "Christmas Island"
countryNameListArr(45)	 = "Cocos Islands"
countryNameListArr(46)	 = "Colombia"
countryNameListArr(47)	 = "Comoros"
countryNameListArr(48)	 = "Congo"
countryNameListArr(49)	 = "Cook Islands"
countryNameListArr(50)	 = "Costa Rica"
countryNameListArr(51)	 = "Croatia"
countryNameListArr(52)	 = "Cuba"
countryNameListArr(53)	 = "Cyprus"
countryNameListArr(54)	 = "Czech Republic"
countryNameListArr(55)	 = "Democratic Republic of the Congo"
countryNameListArr(56)	 = "Democratic Peopleâ€™s Republic of Korea"
countryNameListArr(57)	 = "Denmark"
countryNameListArr(58)	 = "Djibouti"
countryNameListArr(59)	 = "Dominican Republic"
countryNameListArr(60)	 = "East Timor"
countryNameListArr(61)	 = "Ecuador"
countryNameListArr(62)	 = "Egypt"
countryNameListArr(63)	 = "El Salvador"
countryNameListArr(64)	 = "Equatorial Guinea"
countryNameListArr(65)	 = "Eritrea"
countryNameListArr(66)	 = "Estonia"
countryNameListArr(67)	 = "Ethiopia"
countryNameListArr(68)	 = "FalklandIslands"
countryNameListArr(69)	 = "FaroeIslands"
countryNameListArr(70)	 = "Fiji"
countryNameListArr(71)	 = "Finland"
countryNameListArr(72)	 = "France"
countryNameListArr(73)	 = "French Guyana"
countryNameListArr(74)	 = "Gabon"
countryNameListArr(75)	 = "Gambia"
countryNameListArr(76)	 = "Georgia"
countryNameListArr(77)	 = "Germany"
countryNameListArr(78)	 = "Ghana"
countryNameListArr(79)	 = "Gibraltar"
countryNameListArr(80)	 = "Greece"
countryNameListArr(81)	 = "Greenland"
countryNameListArr(82)	 = "Grenada"
countryNameListArr(83)	 = "Guadeloupe"
countryNameListArr(84)	 = "Guam"
countryNameListArr(85)	 = "Guatemala"
countryNameListArr(86)	 = "Guinea"
countryNameListArr(87)	 = "Guinea Bissau"
countryNameListArr(88)	 = "Guyana"
countryNameListArr(89)	 = "Haiti"
countryNameListArr(90)	 = "Honduras"
countryNameListArr(91)	 = "Hong Kong"
countryNameListArr(92)	 = "Hungary"
countryNameListArr(93)	 = "Iceland"
countryNameListArr(94)	 = "India"
countryNameListArr(95)	 = "Indonesia"
countryNameListArr(96)	 = "Iran"
countryNameListArr(97)	 = "Iraq"
countryNameListArr(98)	 = "Ireland"
countryNameListArr(99)	 = "Israel"
countryNameListArr(100)	 = "Italy"
countryNameListArr(101)	 = "Ivory Coast"
countryNameListArr(102)	 = "Jamaica"
countryNameListArr(103)	 = "Japan"
countryNameListArr(104)	 = "Jordan"
countryNameListArr(105)	 = "Kazakhstan"
countryNameListArr(106)	 = "Kenya"
countryNameListArr(107)	 = "Kiribati"
countryNameListArr(108)	 = "Kosovo"
countryNameListArr(109)	 = "Kuwait"
countryNameListArr(110)	 = "Kyrgyzstan"
countryNameListArr(111)	 = "Lao Peopleâ€™s Democratic republic"
countryNameListArr(112)	 = "Latvia"
countryNameListArr(113)	 = "Lebanon"
countryNameListArr(114)	 = "Lesotho"
countryNameListArr(115)	 = "Liberia"
countryNameListArr(116)	 = "Libya"
countryNameListArr(117)	 = "Liechtenstein"
countryNameListArr(118)	 = "Lithuania"
countryNameListArr(119)	 = "Luxembourg"
countryNameListArr(120)	 = "Macau"
countryNameListArr(121)	 = "Macedonia"
countryNameListArr(122)	 = "Madagascar"
countryNameListArr(123)	 = "Malawi"
countryNameListArr(124)	 = "Malaysia"
countryNameListArr(125)	 = "Mali"
countryNameListArr(126)	 = "Malta"
countryNameListArr(127)	 = "Marshall Islands"
countryNameListArr(128)	 = "Martinique"
countryNameListArr(129)	 = "Mauritania"
countryNameListArr(130)	 = "Mauritius"
countryNameListArr(131)	 = "Mayotte"
countryNameListArr(132)	 = "Mexico"
countryNameListArr(133)	 = "Micronesia"
countryNameListArr(134)	 = "Moldova"
countryNameListArr(135)	 = "Monaco"
countryNameListArr(136)	 = "Mongolia"
countryNameListArr(137)	 = "Montenegro"
countryNameListArr(138)	 = "Montserrat"
countryNameListArr(139)	 = "Morocco"
countryNameListArr(140)	 = "Mozambique"
countryNameListArr(141)	 = "Myanmar"
countryNameListArr(142)	 = "Namibia"
countryNameListArr(143)	 = "Nauru"
countryNameListArr(144)	 = "Nepal"
countryNameListArr(145)	 = "Netherlands"
countryNameListArr(146)	 = "Netherlands Antilles"
countryNameListArr(147)	 = "Neutral Zone"
countryNameListArr(148)	 = "New Caledonia"
countryNameListArr(149)	 = "New Zealand"
countryNameListArr(150)	 = "Nicaragua"
countryNameListArr(151)	 = "Niger"
countryNameListArr(152)	 = "Nigeria"
countryNameListArr(153)	 = "Niue"
countryNameListArr(154)	 = "Norfolk Island"
countryNameListArr(155)	 = "Norway"
countryNameListArr(156)	 = "Oman"
countryNameListArr(157)	 = "Pakistan"
countryNameListArr(158)	 = "Palau"
countryNameListArr(159)	 = "Panama"
countryNameListArr(160)	 = "Papua New Guinea"
countryNameListArr(161)	 = "Paraguay"
countryNameListArr(162)	 = "Peru"
countryNameListArr(163)	 = "Philippines"
countryNameListArr(164)	 = "Pitcairn Island"
countryNameListArr(165)	 = "Poland"
countryNameListArr(166)	 = "Polynesia"
countryNameListArr(167)	 = "Portugal"
countryNameListArr(168)	 = "Puerto Rico"
countryNameListArr(169)	 = "Qatar"
countryNameListArr(170)	 = "Republic of Maldives"
countryNameListArr(171)	 = "Reunion"
countryNameListArr(172)	 = "Romania"
countryNameListArr(173)	 = "Russian Federation"
countryNameListArr(174)	 = "Rwanda"
countryNameListArr(175)	 = "Saint Helena"
countryNameListArr(176)	 = "Saint Kitts and Nevis"
countryNameListArr(177)	 = "Saint Lucia"
countryNameListArr(178)	 = "Saint Vincent and The Grenadines"
countryNameListArr(179)	 = "San Marino"
countryNameListArr(180)	 = "Sao Tome and Principe"
countryNameListArr(181)	 = "Saudi Arabia"
countryNameListArr(182)	 = "Senegal"
countryNameListArr(183)	 = "Serbia"
countryNameListArr(184)	 = "Seychelles"
countryNameListArr(185)	 = "Sierra Leone"
countryNameListArr(186)	 = "Singapore"
countryNameListArr(187)	 = "Slovakia"
countryNameListArr(188)	 = "Slovenia"
countryNameListArr(189)	 = "Solomon Islands"
countryNameListArr(190)	 = "Somalia"
countryNameListArr(191)	 = "South Africa"
countryNameListArr(192)	 = "Spain"
countryNameListArr(193)	 = "SriLanka"
countryNameListArr(194)	 = "Sudan"
countryNameListArr(195)	 = "Suriname"
countryNameListArr(196)	 = "Swaziland"
countryNameListArr(197)	 = "Sweden"
countryNameListArr(198)	 = "Switzerland"
countryNameListArr(199)	 = "Syria"
countryNameListArr(200)	 = "Tadjikistan"
countryNameListArr(201)	 = "Taiwan"
countryNameListArr(202)	 = "Thailand"
countryNameListArr(203)	 = "Togo"
countryNameListArr(204)	 = "Tokelau"
countryNameListArr(205)	 = "Tonga"
countryNameListArr(206)	 = "Trinidad Tobago"
countryNameListArr(207)	 = "Tunisia"
countryNameListArr(208)	 = "Turkey"
countryNameListArr(209)	 = "Turkmenistan"
countryNameListArr(210)	 = "Tuvalu"
countryNameListArr(211)	 = "Uganda"
countryNameListArr(212)	 = "Ukraine"
countryNameListArr(213)	 = "United Arab Emirates"
countryNameListArr(214)	 = "United Kingdom"
countryNameListArr(215)	 = "United Republic of Tanzania"
countryNameListArr(216)	 = "United States of America"
countryNameListArr(217)	 = "Uruguay"
countryNameListArr(218)	 = "Uzbekistan"
countryNameListArr(219)	 = "Vanuatu"
countryNameListArr(220)	 = "Vatican City State"
countryNameListArr(221)	 = "Venezuela"
countryNameListArr(222)	 = "Vietnam"
countryNameListArr(223)	 = "Virgin Islands(British)"
countryNameListArr(224)	 = "Virgin Islands(USA)"
countryNameListArr(225)	 = "Wallisand Futuna Islands"
countryNameListArr(226)	 = "Western Sahara"
countryNameListArr(227)	 = "Western Samoa"
countryNameListArr(228)	 = "Yemen"
countryNameListArr(229)	 = "Zaire"
countryNameListArr(230)	 = "Zambia"
countryNameListArr(231)	 = "Zimbabwe"







' ------------------------------------------------------------------------------
' ±¹°¡¸í Select Menu Html
Public Sub countryListView()
    Dim i
    response.write "<option value="""">=====================</option>"
    for i=0 to uBound(countryNameListArr)
        response.write "<option value="""&countryNameListArr(i)&""" title="""&countryNameListArr(i)&""">"&countryNameListArr(i)&"</option>"
    next
End Sub

Public Sub countryListSelect(ct)
    Dim i, selectFlag
    response.write "<option value="""">- select a Country/Region -</option>"
    for i=0 to uBound(countryNameListArr)
        if countryNameListArr(i)=ct then
											 selectFlag = " selected"
								else
												selectFlag = ""
								end if
								response.write "<option value="""&countryNameListArr(i)&""" title="""&countryNameListArr(i)&""""&selectFlag&">"&countryNameListArr(i)&"</option>"
    next
End Sub



Public Sub abs_countryListSelect(ct)
    Dim i, selectFlag
    response.write "<option value=''>- select a Country/Region -</option>"
    for i=0 to uBound(countryNameListArr)
        if countryNameListArr(i)=ct then
											 selectFlag = " selected"
								else
												selectFlag = ""
								end if
								response.write "<option value='"&countryNameListArr(i)&"' title='"&countryNameListArr(i)&"' "&selectFlag&">"&countryNameListArr(i)&"</option>"
    next
End Sub

' ------------------------------------------------------------------------------
%>